# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  displayName: Get azure account details for ansible
  inputs:
    azureSubscription: 'AzureServiceConnection'
    addSpnToEnvironment: true
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(az account show --query="id" -o tsv)"
      echo "##vso[task.setvariable variable=ARM_CLIENT_ID]${servicePrincipalId}"
      echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET]${servicePrincipalKey}"
      echo "##vso[task.setvariable variable=ARM_TENANT_ID]${tenantId}"

- script: |
    pip install "ansible==2.9.17"
    pip install ansible[azure]
  displayName: 'Install Ansible'

- script: |
    cat /dev/zero | ssh-keygen -q -N ""
    cd azenv
    ansible-playbook -i hosts main.yml
    ansible-playbook -i ansiblehost deploysw.yml
  displayName: 'Run infrastructure deployment and ansible installation playbooks'
  env:
    AZURE_CLIENT_ID: $(ARM_CLIENT_ID)
    AZURE_SECRET: $(ARM_CLIENT_SECRET)
    AZURE_TENANT: $(ARM_TENANT_ID)
    AZURE_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)

- task: AzureCLI@2
  displayName: Update ssh key on web and db servers
  inputs:
    azureSubscription: 'AzureServiceConnection'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './azenv/sshkeyupdate.sh'

- script: |
    ssh -tt -oStrictHostKeyChecking=accept-new $(cat azenv/ansiblehost | grep "\." | cut -d' ' -f 2 | cut -d'=' -f 2)@$(cat azenv/ansiblehost | grep "\." | cut -d' ' -f 1) "cd lamp && ansible-playbook -i hosts site.yml"
    ansible-playbook -i hosts rmansvm.yml
  displayName: Run lamp playbook, delete temp ansible vm
  env:
    AZURE_CLIENT_ID: $(ARM_CLIENT_ID)
    AZURE_SECRET: $(ARM_CLIENT_SECRET)
    AZURE_TENANT: $(ARM_TENANT_ID)
    AZURE_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)

- script: |
    cat azenv/web1ip
    curl $(cat azenv/web1ip)
  displayName: Access lamp website