---
- hosts: all
  become: yes
  gather_facts: no

  tasks:

    - name: Wait 600 seconds for target connection to become reachable/usable
      wait_for_connection:

    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Install python3-pip
      yum:
        name: python3-pip
        update_cache: yes
        state: present

    - name: upgrade pip
      pip:
        name: pip
        state: latest

    - name: Install ansible
      pip:
        name: ansible==2.9.17

    - name: install epel-release and update dnf cache 
      dnf:
        name: epel-release
        update_cache: yes

    - name: Copy lamp folder
      become: no
      ansible.builtin.copy:
        src: ../lamp
        dest: ~/

    - name: Copy id_rsa
      become: no
      ansible.builtin.copy:
        src: ~/.ssh/id_rsa
        dest: ~/.ssh/
        mode: 0600

    - name: Copy id_rsa.pub
      become: no
      ansible.builtin.copy:
        src: ~/.ssh/id_rsa.pub
        dest: ~/.ssh/
        mode: 0644
