- name: Install chrony
  dnf:
    name: chrony
    state: present
  tags: chrony

- name: Configure chrony file
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  tags: chrony
  notify: restart chronyd

- name: Start the chronyd service
  service:
    name: chronyd
    state: started
    enabled: yes
  tags: chronyd

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false
